version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    secrets:
      - pg-passwd
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - pg-passwd
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg-passwd
      - POSTGRES_DB=leafy
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./config/nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 8000:80
    depends_on:
      - backend

volumes:
  pg-data:

secrets:
  pg-passwd:
    file: config/db/postgres/passwd.txt